# Site
name: "Save Nivesh"
title: "Save Nivesh"
description: "Trying to explain the interesting stuff in investing space. Stocks, MF, Personal Finance, Crypto!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
domain: tushargg.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://tushargg.github.io
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'savenivesh'
mailchimp-list: '#'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: "#"

# Authors
authors:
  alien:
    name: Alien
    display_name: Alien
    avatar: 'assets/images/avatar-sal.png'
    email: hi@gmail.com
    web: '#'
    twitter: '#'
    description: "Descr jsjk jskjfkjsk"
  # john:
  #   name: John
  #   display_name: John    
  #   avatar: 'assets/images/avatar.png'
  #   email: wowthemesnet@gmail.com
  #   web: https://www.wowthemes.net
  #   twitter: https://twitter.com/wowthemesnet
  #   description: "Write a short description of the author here. You are currently previewing Memoirs demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
